---
# Author: Jorge Hevia - jmhev@outlook.com
# What does this role do?: this role starts an ec2 instance, then mysql and replicates
#                         the content of the DB with it's master.

# TO-DO: DO NOT EXECUTE IF MASTER INSTANCE IS DOWN
#- include: start-instances.yml
#- include: start-mysql.yml
- include: mysql-replication.yml
#- include: stop-instances.yml
